# change focus
bindsym $mod+h exec --no-startup-id easy-i3-neovim-nav focus left
bindsym $mod+j exec --no-startup-id easy-i3-neovim-nav focus down
bindsym $mod+k exec --no-startup-id easy-i3-neovim-nav focus up
bindsym $mod+l exec --no-startup-id easy-i3-neovim-nav focus right

# Change focus with control
bindsym Control+h exec --no-startup-id easy-i3-neovim-nav focus left
bindsym Control+j exec --no-startup-id easy-i3-neovim-nav focus down
bindsym Control+k exec --no-startup-id easy-i3-neovim-nav focus up
bindsym Control+l exec --no-startup-id easy-i3-neovim-nav focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left  exec --no-startup-id easy-i3-neovim-nav focus left
bindsym $mod+Down  exec --no-startup-id easy-i3-neovim-nav focus down
bindsym $mod+Up    exec --no-startup-id easy-i3-neovim-nav focus up
bindsym $mod+Right exec --no-startup-id easy-i3-neovim-nav focus right

# resize window (you can also use the mouse for that)
mode "resize" {
	bindsym h exec --no-startup-id easy-i3-neovim-nav resize shrink width  5 10 5
	bindsym j exec --no-startup-id easy-i3-neovim-nav resize shrink height 5 10 5
	bindsym k exec --no-startup-id easy-i3-neovim-nav resize grow   height 5 10 5
	bindsym l exec --no-startup-id easy-i3-neovim-nav resize grow   width  5 10 5

	bindsym Left  exec --no-startup-id easy-i3-neovim-nav resize shrink width  5 10 5
	bindsym Down  exec --no-startup-id easy-i3-neovim-nav resize shrink height 5 10 5
	bindsym Up    exec --no-startup-id easy-i3-neovim-nav resize grow   height 5 10 5
	bindsym Right exec --no-startup-id easy-i3-neovim-nav resize grow   width  5 10 5

	# exit resize mode
	bindsym Return mode "default"
	bindsym Escape mode "default"
	bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"
