# Touchpad: natural scrolling + tapping
exec --no-startup-id xinput set-prop "SYNA8018:00 06CB:CE67 Touchpad" "libinput Natural Scrolling Enabled" 1
exec --no-startup-id xinput set-prop "SYNA8018:00 06CB:CE67 Touchpad" "libinput Tapping Enabled" 1
exec --no-startup-id xinput set-prop "SYNA8018:00 06CB:CE67 Touchpad" "libinput Tapping Drag Enabled" 1
exec --no-startup-id xinput set-prop "SYNA8018:00 06CB:CE67 Touchpad" "libinput Tapping Button Mapping Enabled" 1

# Put DP 3 on top of the internal display
exec --no-startup-id xrandr --output DP-3-3 --auto --above eDP-1
